name: frd
description: A Flutter Research and Development project.
publish_to: "none"
version: 1.0.1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  dio: ^5.8.0+1
  http: ^1.3.0
  provider: ^6.1.4
  get_it: ^8.0.3
  equatable: ^2.0.7
  rxdart: ^0.28.0
  permission_handler: ^11.4.0
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  logger: ^2.5.0
  meta: ^1.16.0
  path: ^1.9.1
  path_provider: ^2.1.5
  firebase_auth: ^5.5.1
  firebase_dynamic_links: ^6.1.4
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  intl: ^0.19.0
  uuid: ^4.5.1
  flutter_local_notifications: ^19.0.0
  google_sign_in: ^6.3.0
  flutter_facebook_auth: ^7.1.1
  sign_in_with_apple: ^6.1.4
  video_player: ^2.9.5
  chewie: ^1.11.0
  syncfusion_flutter_calendar: ^29.1.33
  persistent_bottom_nav_bar: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  integration_test:
    sdk: flutter
  mockingjay: ^1.0.0
  mocktail: ^1.0.4
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/audios/
    - assets/videos/
    - assets/captions/
    - assets/json/

  fonts:
    - family: lexend
      fonts:
        - asset: assets/fonts/Lexend-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lexend-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lexend-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lexend-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lexend-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Lexend-Black.ttf
          weight: 900

flutter_intl:
  enabled: true
