name: frd
description: A Flutter Research and Development project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  dio: ^5.3.2
  http: ^1.1.0
  provider: ^6.0.5
  get_it: ^7.6.0
  equatable: ^2.0.5
  rxdart: ^0.27.7
  permission_handler: ^10.4.3
  shared_preferences: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  logger: ^2.0.1
  meta: ^1.9.1
  path: ^1.8.3
  path_provider: ^2.1.0
  firebase_auth: ^4.7.2
  firebase_dynamic_links: ^5.0.17
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  intl: ^0.18.0
  uuid: ^3.0.7
  flutter_local_notifications: ^15.1.0+1
  google_sign_in: ^6.1.4
  flutter_facebook_auth: ^6.0.1
  sign_in_with_apple: ^5.0.0
  video_player: ^2.7.0
  chewie: ^1.7.0
  syncfusion_flutter_calendar: ^22.2.8
  persistent_bottom_nav_bar: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.4
  integration_test:
    sdk: flutter
  mockingjay: ^0.3.0
  mocktail: ^0.3.0
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/audios/
    - assets/videos/
    - assets/captions/
    - assets/json/

  fonts:
    - family: lexend
      fonts:
        - asset: assets/fonts/Lexend-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lexend-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lexend-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lexend-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lexend-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Lexend-Black.ttf
          weight: 900

flutter_intl:
  enabled: true
